# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

corC <- function(x, y) {
    .Call('Reot_corC', PACKAGE = 'Reot', x, y)
}

lmC <- function(x, y) {
    .Call('Reot_lmC', PACKAGE = 'Reot', x, y)
}

predRsquaredSum <- function(pred_vals, resp_vals, standardised) {
    .Call('Reot_predRsquaredSum', PACKAGE = 'Reot', pred_vals, resp_vals, standardised)
}

respLmParam <- function(x, y, cell) {
    .Call('Reot_respLmParam', PACKAGE = 'Reot', x, y, cell)
}

